services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    networks:
      - local_safe_net
    container_name: webconstad_web
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
      - /app/frontend/node_modules
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - webconstad_media:/app/media
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    networks:
      - local_safe_net
    container_name: webconstad_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - webconstad_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  webconstad_db_data:
  webconstad_media:

networks:
  local_safe_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24
