# Generated by Django 6.0.3 on 2026-03-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_orden_estado_alter_orden_moneda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='paginas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
