# Generated by Django 6.0.3 on 2026-04-17 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_producto_paginas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=120)),
                ('imagen', models.URLField(blank=True)),
                ('es_gratuita', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria_gratuita',
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='imagen_portada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='archivo_url',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_preview',
        ),
        migrations.AddField(
            model_name='coleccion',
            name='imagen',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='archivo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='web.categoria'),
        ),
        migrations.DeleteModel(
            name='CategoriaGratuita',
        ),
    ]
