# Generated by Django 6.0.3 on 2026-04-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_categoria_remove_producto_categoria_gratuita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/iconos/'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/portadas/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='archivo',
            field=models.FileField(upload_to='productos/archivos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/previews/'),
        ),
    ]
