# Generated by Django 6.0.3 on 2026-04-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_categoria_icono_alter_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
    ]
