# Generated by Django 6.0.3 on 2026-04-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_categoria_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='colecciones/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
