# Generated by Django 6.0.3 on 2026-04-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_categoria_imagen_alter_coleccion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Admin')], default='cliente', max_length=20),
        ),
    ]
