# Generated by Django 6.0.3 on 2026-04-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_perfilcliente_rol_alter_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscriptorAnonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscriptor anonimo',
                'verbose_name_plural': 'Suscriptores anonimos',
            },
        ),
    ]
