# Generated by Django 6.0.3 on 2026-04-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_suscriptoranonimo_alter_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='frontend', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('error', 'Error')], default='ready', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Build state',
                'verbose_name_plural': 'Build states',
            },
        ),
    ]
