# Generated by Django 6.0.3 on 2026-04-25 03:25

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_buildstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='colecciones/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='productos/'),
        ),
    ]
