# Generated by OpenCode on 2026-04-29

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_categoria_imagen_alter_coleccion_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='descripcion',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='colecciones/descripciones/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='preview_imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='productos/previews/'),
        ),
    ]
