# Generated by Django 6.0.3 on 2026-05-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_coleccion_descripcion_imagen_and_producto_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_gratuito',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
