# Generated by Django 6.0.3 on 2026-05-08 02:01

import storages.backends.s3
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_merge_0015_producto_descripcion_imagen_y_quitar_coleccion_descripcion_0016_mensajecontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(custom_domain='pub-9d4134ed1b5c4103860ffc5f4bf17da8.r2.dev', querystring_auth=False), upload_to='categorias/', validators=[web.models.validate_image_extension, web.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(custom_domain='pub-9d4134ed1b5c4103860ffc5f4bf17da8.r2.dev', querystring_auth=False), upload_to='colecciones/', validators=[web.models.validate_image_extension, web.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='productos/', validators=[web.models.validate_file_extension, web.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(custom_domain='pub-9d4134ed1b5c4103860ffc5f4bf17da8.r2.dev', querystring_auth=False), upload_to='productos/descripciones/', validators=[web.models.validate_image_extension, web.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_gratuito',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(custom_domain='pub-9d4134ed1b5c4103860ffc5f4bf17da8.r2.dev', querystring_auth=False), upload_to='productos/', validators=[web.models.validate_image_extension, web.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='preview_imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(custom_domain='pub-9d4134ed1b5c4103860ffc5f4bf17da8.r2.dev', querystring_auth=False), upload_to='productos/previews/', validators=[web.models.validate_image_extension, web.models.validate_image_size]),
        ),
    ]
