# Generated by Django 6.0.3 on 2026-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_categoria_imagen_alter_coleccion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_extendida',
            field=models.TextField(blank=True),
        ),
    ]
