# Generated by Django 6.0.3 on 2026-05-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_categoria_imagen_alter_coleccion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='flow_card_bank',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='flow_card_last4',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='flow_card_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='flow_customer_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
