name: Deploy Production

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Desplegar en el producción vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            set -e
            cd /home/nicolas/webconstAD

            git config --global --add safe.directory $(pwd)
            git fetch --all --tags
            git reset --hard origin/main

            export APP_VERSION=${{ github.ref_name }}
            docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml up -d --force-recreate
