name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en el servidor vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/nicolas/webconstAD

            git config --global --add safe.directory $(pwd)
            git fetch --tags origin
            git reset --hard ${{ github.ref_name }}

            export APP_VERSION=${{ github.ref_name }}
            docker compose up -d --build --force-recreate
