from django.urls import path
from . import views

urlpatterns = [
    path('api/', views.api_root, name='api-root'),
    path('api/health/', views.api_health, name='api-health'),
    path('api/pagos/detalle/', views.api_payment_details, name='api-payment-details'),
    path('api/productos/', views.api_products, name='api-products'),
    path('api/productos/<slug:slug>/', views.api_producto_detalle, name='api-producto-detalle'),
    path('api/categorias/', views.api_categorias, name='api-categorias'),
    path('api/catalog/categorias/', views.api_catalog_categorias, name='api-catalog-categorias'),
    path('api/catalog/colecciones/', views.api_catalog_colecciones, name='api-catalog-colecciones'),
    path('api/categorias/<slug:slug>/productos/', views.api_categoria_productos, name='api-categoria-productos'),
    path('api/auth/csrf/', views.api_auth_csrf, name='api-auth-csrf'),
    path('api/auth/register/', views.api_auth_register, name='api-auth-register'),
    path('api/auth/login/', views.api_auth_login, name='api-auth-login'),
    path('api/auth/logout/', views.api_auth_logout, name='api-auth-logout'),
    path('api/auth/session/', views.api_auth_session, name='api-auth-session'),
    path('api/auth/account/update/', views.api_auth_account_update, name='api-auth-account-update'),
    path('api/newsletter/suscribir/', views.api_suscriptor_anonimo_crear, name='api-newsletter-suscribir'),
    path('api/publicar/producto/', views.api_publicar_producto, name='api-publicar-producto'),
    path('api/admin/productos/', views.api_admin_productos, name='api-admin-productos'),
    path('api/admin/productos/<int:producto_id>/editar/', views.api_admin_producto_editar, name='api-admin-producto-editar'),
    path('api/admin/productos/<int:producto_id>/eliminar/', views.api_admin_producto_eliminar, name='api-admin-producto-eliminar'),
    path('api/admin/catalogo/crear/', views.api_admin_catalogo_crear, name='api-admin-catalogo-crear'),
    path('api/admin/catalogo/<str:tipo>/<int:item_id>/editar/', views.api_admin_catalogo_editar, name='api-admin-catalogo-editar'),
    path('api/admin/catalogo/<str:tipo>/<int:item_id>/eliminar/', views.api_admin_catalogo_eliminar, name='api-admin-catalogo-eliminar'),
    path('api/productos/<slug:slug>/download/', views.api_producto_download, name='api-producto-download'),
    path('api/cart/', views.api_cart, name='api-cart'),
    path('api/cart/add/', views.api_cart_add, name='api-cart-add'),
    path('api/cart/items/<int:item_id>/', views.api_cart_item_delete, name='api-cart-item-delete'),
    path('api/cart/checkout/', views.api_cart_checkout, name='api-cart-checkout'),
    path('api/pagos/flow/create-payment/', views.api_flow_create_payment, name='api-flow-create-payment'),
    path('api/pagos/flow/confirmacion/', views.api_flow_confirmation, name='api-flow-confirmation'),
    path('api/pagos/flow/retorno/', views.api_flow_return, name='api-flow-return'),
]
